  version: 2.1
  jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"
    steps:
      - run:
          name: テストの実行
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests
